[package]
name = "java_builder"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name="java_codegen"
harness=false

[dependencies]
tree-sitter = "0.24.4"
tree-sitter-java = "0.23.4"
rand = "0.8.5"
zip = "2.2.2"
